spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true

logging:

  pattern:
    console: '{"time":"%d","level":"%level","tenant":"%X{tenantSlug}","req":"%X{requestId}","user":"%X{userId}","msg":"%msg"}%n'

  level:
    root: WARN
    com.saasplatform: INFO
    org.springframework.security: WARN

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false